### PR TITLE
R Debug CRAN fixes

### PR DESCRIPTION
**Pull request by Mytherin**
* Remove -Wexit-time-destructor pragmas, and instead disable these warnings in specific compilation units using CMake
* Several other MacOS warning fixes
* Many CRAN fixes from Hannes (see [here](https://github.com/hannes/duckdb/commit/d2cc764a70ef1d0ca96f44da36e9d6338349cda7))

### CODE REVIEW

**Comment by hannes** [comment]
Found some more stuff, the beginning of `tools/rpkg/R/backend-dbplyr__duckdb_connection.R` should look like this

```R
#' DuckDB SQL backend for dbplyr
#'
#' @description
#' This is a SQL backend for dbplyr tailored to take into account DuckDB's
#' possibilities. This mainly follows the backend for PostgreSQL, but
#' contains more mapped functions.
#'
#' @name backend-duckdb
#' @aliases NULL
#' @examples
#' library(dplyr, warn.conflicts = FALSE)
#' con <- DBI::dbConnect(duckdb::duckdb(), path = ":memory:")
#'
#' dbiris <- copy_to(con, iris, overwrite = TRUE)
#'
#' dbiris %>% select(Petal.Length, Petal.Width) %>% filter(Petal.Length > 1.5) %>% head(5)
#'
#' DBI::dbDisconnect(con, shutdown = TRUE)
NULL
```

It used to trigger RE2 a lot

**Comment by hannes** [comment]
Also,  the beginning of `test_arrow.R` needs to be more defensive 
```R
skip_on_cran()
skip_on_os("windows")
skip_if_not_installed("dbplyr")
skip_if_not_installed("dplyr")
skip_if_not_installed("arrow", "5.0.0")
# Skip if parquet is not a capability as an indicator that Arrow is fully installed.
skip_if_not(arrow::arrow_with_parquet(), message = "The installed Arrow is not fully featured, skipping Arrow integration tests")

library("DBI")
library("duckdb")
library("dplyr")
```

**Comment by Mytherin** [comment]
Done

**Comment by Mytherin** [comment]
[Passes on my CI now](https://github.com/Mytherin/duckdb/actions/runs/2475647543)

**Pull request merged**
